### ISSUE TITLE
No module named 'ierror' 找不到ierror模块

### ISSUE THREAD

**Issue by 50007** [taiyi747/WeWork-Robot#1]
我往requirements.txt添加了cryptography和ierror这样可以吗？貌似找不到ierror模块，
打包构建成docker后的日志
Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    from WXBizMsgCrypt import WXBizMsgCrypt
  File "/app/WXBizMsgCrypt.py", line 19, in <module>
    import ierror
ModuleNotFoundError: No module named 'ierror'

**Comment by taiyi747** [comment]
我的锅，我漏上传了微信混淆的文件

**Comment by taiyi747** [comment]
func逻辑发现有点问题，明天会更新

**Comment by 50007** [comment]
@taiyi747 可以帮忙看一下收不到gpt回复的信息是怎么回事吗？企业可信IP设置好了的，有什么方法可以排查gemini是否连通
![微信截图_20240221041949](https://github.com/taiyi747/WeWork-Robot/assets/143870542/51b642eb-37cf-48c5-b0e3-fd15708c9cc5)
![微信截图_20240221042034](https://github.com/taiyi747/WeWork-Robot/assets/143870542/1b83553f-c00b-4aca-b6b3-84611f7f2f09)
访问 ip/wechat如下
![微信截图_20240221042424](https://github.com/taiyi747/WeWork-Robot/assets/143870542/d78424cb-e64e-4100-8933-043baf581f9f)

**Comment by taiyi747** [comment]
你这个图看起来没什么问题
可以在func.py的49行下面加个
print(response.status)
看一下是否报的200状态码

**Comment by 50007** [comment]
@taiyi747 
还是没有Gemini的返回数据，可能是我的服务器是香港的访问不了Gemini；
以后是否会增加一个自定义的API接口地址和OPENAI API KEY，创建多个应用可以选择不同的api接口。

**Comment by taiyi747** [comment]
香港的话确实访问不了
你可以自己搭建一个vercel代理
https://github.com/antergone/palm-netlify-proxy
然后修改func.py的第30行那个谷歌api地址

**Comment by taiyi747** [comment]
openai接口我本来也有写好的，只是没有上传
最近比较忙，可能在下一次更新就会增加OpenAI，Gemini等四五种接入方式
最近还没有想好要不要实现一些类似日程助理的功能
