### ISSUE TITLE
企业微信 openapi回调地址请求不通过

### ISSUE THREAD

**Issue by HiJackk** [taiyi747/WeWork-Robot#4]
作者你好，请问在API接收消息里的，URL填写的URL需要正确响应企业微信验证URL的请求
这一步的时候，写了自己的域名，但是提示这个：请问怎么处理呀
企业微信 openapi回调地址请求不通过

**Comment by taiyi747** [comment]
不对，你这个可能要改一行代码允许域名请求
你可以看看域名/WeChat看看能不能通过
